on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: aws-actions/setup-sam@v1
      - run: sam build
      - name: Archive SAM artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sam-arts
          path: |
            .aws-sam/build
